### ISSUE TITLE
Beam isn't working

### ISSUE THREAD

**Issue by davidwim** [finncodes/openscootermap#8]
The Beam API isn't working on this map (No scooters being displayed on the map)

OpenScooterMap website: [https://imgur.com/UqVJBHp](https://imgur.com/UqVJBHp)
Official Beam App: [https://imgur.com/a/im0LzHy](https://imgur.com/a/im0LzHy)

Is this an issue on their end that can't be resolved on our end?

**Comment by finncodes** [comment]
Hi @davidwim,

Thanks for taking the time to get those screenshots and annotate them - I haven't been too sure about what's going on since I'm not located in Christchurch and they help a lot. My current guess is that they've perhaps restricted or changed the API endpoint I was using to get the location of the scooters. Due to the pandemic it's been hard to tell who's either changed their API or just stopped serving regions altogether - I believe Onzo could have closed up shop entirely since I haven't seen any around and their server isn't responding, and Uber may have given up on their Jump scooters here as I have seen Flamingos around but none of theirs.

If you have any logs that show requests between the app and Beam's API servers, those could be very helpful - if you choose to paste any, remember to remove any authorisation headers or session cookies if they're present - you could otherwise accidentally give someone access to your account.

**Comment by davidwim** [comment]
I think I've found what the issue is, it's that the script has a old app version on it. When the "escooterapp/1.17.0; android" is used, there is an error saying "no Route matched with those values" but if I replace the "escooterapp/1.17.0; android" with "escooterapp/1.36.0; ios" the response is comes out fine with all of the Scooter info. Beam stops their old app versions from working if they're a few versions behind. I don't know if it's possible - but you might have to make a script to change the App Version in the Header to the latest every few weeks.

The reason that JUMP aren't in Wellington anymore is because they were bought by Lime, [[Article]](https://techcrunch.com/2020/05/07/uber-leads-170-million-lime-investment-offloads-jump-to-lime/) and also your point about OnzO shutting up shop is most likely true as their has been some media attention about them being unsafe recently. 

I also see that Lime and Bird aren't working either. This is probably because the ScooterMap API is being used. ScooterMap is has had some issues with Lime and they no longer display Lime scooters on ScooterMap. Bird no longer works either. But I see that ScooterMap is still making requests from Lime's API, I found this out by going on to the ScooterMap website and debugging their HTTP traffic. You could probably do the same and use their request info and use it in the script. From what I can tell, it looks like they're using a burner account just for the API as all the info that I've received from the API about the account is untouched.

**Comment by finncodes** [comment]
I'll update the headers for Beam manually for now - in the future I'll look into a way to scrape it from somewhere and use the latest version automatically.

Thanks for the news articles - I completely missed Lime's acquisition of Jump - I'll leave issue #3 open for now since it looks like Jump will still come back through the Uber app. ([article](https://www.stuff.co.nz/dominion-post/news/wellington/121515914/flamingo-gets-the-jump-as-escooters-return-to-city-streets)) I might as well go ahead and remove Onzo though.

How did you find out that ScooterMap was still making requests from Lime's API with a burner account? All I have been able to see are requests going to ScooterMap's own API server. Is there a repo somewhere?

**Comment by davidwim** [comment]
Thank you for reply. I wouldn’t remove Onzo from your script incase they end up surfacing again. 

If you go onto the ScooterMap website, make sure you have Lime as a provider enabled and go into the Chrome Developer tools (inspect element) then go into the network tab and move the map around you will see a whole lot of requests appear. Lime is one of the requests that is in red text, if it starts with something like web-production.lime.bike, right click and copy as cURL. Import the code into your API sender thing (mine is Postman) and you should receive a response.

The reason I think it’s just an account intended for API uses is because the account hasn’t got any rides/personal info (e.g. Name, Email, Payment Info, etc)

**Comment by finncodes** [comment]
@davidwim Sorry about the late reply - over the last month every now and then I've been trying to find the Lime requests on the ScooterMap website but I don't see any requests made to Lime themselves - just to a ScooterMap server for a Lime "auth code" when I move the map around. This is what I'm getting:

![image](https://user-images.githubusercontent.com/10346401/89772601-65cfa980-db56-11ea-8e4e-0f2a1c6f2eb7.png)

Perhaps Lime noticed and stopped them from accessing their servers? I'm guessing the reason why I don't see a request to Lime is because this request is failing first.

**Comment by davidwim** [comment]
Maybe it's because you haven't Logged In or haven't enabled Lime in the filters tab at the bottom left corner, you need to also make sure that ScooterMap is picking up scooters on the Rider Side. I've just tried again and Lime responses are still showing up. I'm using the Network Tab in Chrome Devoloper tools to view the requests. Here's a Image on the requests that are going to Lime themselves:
![Screen Shot 2020-08-11 at 4 32 13 PM](https://user-images.githubusercontent.com/63693881/89858138-f60efc80-dbf1-11ea-8b04-9a1749f632ed.png)

You may want to try using Chrome Devoloper Tools if you haven't tried it already. I can Copy the cURL from the request and paste it inside of here if you want.

**Comment by davidwim** [comment]
The version header is still required, but it doesn't matter what version it is anymore.
